const calculatePixelsFromPoints = require('./calculate-pixels-from-points/index')
const currency = require('./currency/index')
const getKeyByValue = require('./get-key-by-value/index')
const hasTrailingSlash = require('./has-trailing-slash/index')
const initialCapitalLetter = require('./initial-capital-letter/index')
const add = require('./math/add/index')
const subtract = require('./math/subtract/index')
const multiply = require('./math/multiply/index')
const divide = require('./math/divide/index')
const percentage = require('./math/percentage/index')
const numberizeValue = require('./numberize-value/index')
const randomNumber = require('./random-number/index')
const salt = require('./salt/index')
const sortAsc = require('./sort/asc/index')
const sortDesc = require('./sort/desc/index')
const titleCase = require('./title-case/index')

const sentence = 'lorem ipsum dolor sit amet'
const value = '123.45px'
const url = 'www.example.com/category'
const urlSlash = 'www.example.com/category/'
const arr = [3,5,8,3,6,5,8,1,1,1,0]

console.log(`calculatePixelsFromPoints(12)`, calculatePixelsFromPoints(12))
console.log(`calculatePixelsFromPoints(12, 96)`, calculatePixelsFromPoints(12, 96))
console.log(`currency(1234567.890)`, currency(1234567.890))
console.log(`currency(1234567.890, '$)`, currency(1234567.890, '$'))
console.log(`getKeyByValue({ name: 'Thom', age: 40 }, 'Thom')`, getKeyByValue({ name: 'Thom', age: 40 }, 'Thom'))
console.log(`hasTrailingSlash(${url})`, hasTrailingSlash(url))
console.log(`hasTrailingSlash(${urlSlash})`, hasTrailingSlash(urlSlash))
console.log(`add(1, 2)`, add(1, 2))
console.log(`subtract(1, 2)`, subtract(1, 2))
console.log(`multiply(1, 2)`, multiply(1, 2))
console.log(`divide(1, 2)`, divide(1, 2))
console.log(`percentage(1, 2)`, percentage(1, 2))
console.log(`initialCapitalLetter(${sentence})`, initialCapitalLetter(sentence))
console.log(`numberizeValue(${value})`, numberizeValue(value))
console.log(`randomNumber()`, randomNumber())
console.log(`salt()`, salt())
console.log(`sortAsc(${ arr })`, sortAsc(arr))
console.log(`sortDesc(${ arr })`, sortDesc(arr))
console.log(`titleCase(${sentence})`, titleCase(sentence))